spring:
  application:
    name: rag-assistant
  ai:
    openai:
      chat:
        api-key: ${OPENROUTER_API_KEY}
        base-url: https://openrouter.ai/api
        options:
          model: gpt-4o-mini
      embedding:
        api-key: ${OPENAI_API_KEY}
        base-url: https://api.openai.com
        options:
          model: text-embedding-3-small
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST:localhost}
        port: 6334
        collection-name: rag-docs
        use-tls: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000
